### ISSUE TITLE
Arquitectura de Solucion

### ISSUE THREAD

**Issue by robinsound** [ViajerosAdoquier/GeoAdoquier#1]
Breve análisis de la solucion propuesta basada en el problema:

Finalmente usaremos google maps, para ello tendremos que crear un metodo que recoja un string y lance la busqueda contra nuestra base de datos, si no encuentra ningun resultado lanzar la peticion contra la API de googlemaps, guardar el registro y devolver los resultados.

**Comment by robinsound** [comment]
Podemos usar una arquitectura simple de `api rpc` para `wrappear` las peticiones a `Google Maps API` y mantener un cache de peticiones (`requests`) y resultados (`responses`) en `redis`. Todo los nuevos `responses` se van guardando en `mongo db` para recargar el `cache`.

Luego para explotar direcciones grandes o especificas, usamos un proceso de carga (`load thread`) vigilado por un guardian (`god`) y asi garantizamos que ocurra de forma continua

**Comment by ViajerosAdoquier** [comment]
Perfecto, entiendo que con esto quedan las siguientes estructuras:

Buscador (cliente) -> API ->   Cache Redis    ->    MongoDB   ->  GoogleMaps

De forma que primero se mira la cache, sino vamos a mongo y si tampoco se encuentra el registro se pide a la API de googleMaps y se hace el proceso inverso para devolver los resultados
